# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SuperDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'A4LoadMeasure'
  # Pods for SuperDemo

end
