# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SuperDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  pod 'SDCycleScrollView','>= 1.82'
  # Pods for SuperDemo
#  pod "Aspects"
#  pod "MLeaksFinder"
    pod 'YYKit', '~> 1.0.9'
end
